-- MySQL Script generated by MySQL Workbench
-- Sat Mar 10 03:08:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema UPFinder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UPFinder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UPFinder` ;
USE `UPFinder` ;

-- -----------------------------------------------------
-- Table `UPFinder`.`Budgets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`Budgets` (
  `BudgetID` INT NOT NULL,
  `AmountMoney` FLOAT NOT NULL,
  PRIMARY KEY (`BudgetID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`UniversityLogic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`UniversityLogic` (
  `SystemID` INT NOT NULL,
  `Name` VARCHAR(40) NULL,
  `BudgetID` INT NOT NULL,
  PRIMARY KEY (`SystemID`),
  INDEX `fk_UniversityLogic_Budget1_idx` (`BudgetID` ASC),
  CONSTRAINT `fk_UniversityLogic_Budget1`
    FOREIGN KEY (`BudgetID`)
    REFERENCES `UPFinder`.`Budgets` (`BudgetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`Spaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`Spaces` (
  `SpaceID` INT NOT NULL,
  `Capacity` INT NULL DEFAULT NULL,
  `Location` VARCHAR(20) NULL DEFAULT NULL,
  `SystemID` INT NOT NULL,
  PRIMARY KEY (`SpaceID`),
  INDEX `fk_Spaces_UniversityLogic1_idx` (`SystemID` ASC),
  CONSTRAINT `fk_Spaces_UniversityLogic1`
    FOREIGN KEY (`SystemID`)
    REFERENCES `UPFinder`.`UniversityLogic` (`SystemID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`Offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`Offices` (
  `SpaceID` INT NOT NULL,
  INDEX `fk_Office_Spaces1_idx` (`SpaceID` ASC),
  PRIMARY KEY (`SpaceID`),
  CONSTRAINT `fk_Office_Spaces1`
    FOREIGN KEY (`SpaceID`)
    REFERENCES `UPFinder`.`Spaces` (`SpaceID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`LibraryWorkingAreas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`LibraryWorkingAreas` (
  `SpaceID` INT NOT NULL,
  INDEX `fk_LibraryWorkingArea_Spaces1_idx` (`SpaceID` ASC),
  PRIMARY KEY (`SpaceID`),
  CONSTRAINT `fk_LibraryWorkingArea_Spaces1`
    FOREIGN KEY (`SpaceID`)
    REFERENCES `UPFinder`.`Spaces` (`SpaceID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`Degrees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`Degrees` (
  `DegreeId` INT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`DegreeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`Users` (
  `UserID` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Surname` VARCHAR(20) NOT NULL,
  `BirthDate` DATE NULL DEFAULT NULL,
  `Email` VARCHAR(20) NOT NULL,
  `StartingDate` DATE NULL DEFAULT NULL,
  `IsActive` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`));


-- -----------------------------------------------------
-- Table `UPFinder`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`Employees` (
  `UserID` INT NOT NULL,
  `Salary` INT NOT NULL,
  PRIMARY KEY (`UserID`),
  INDEX `fk_Employees_Users1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Employees_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `UPFinder`.`Users` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `UPFinder`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`Departments` (
  `DepartmentID` INT NOT NULL,
  `Name` VARCHAR(40) NULL,
  `BudgetID` INT NOT NULL,
  `SpaceID` INT NOT NULL,
  PRIMARY KEY (`DepartmentID`),
  INDEX `fk_Departments_Budget1_idx` (`BudgetID` ASC),
  INDEX `fk_Departments_Office1_idx` (`SpaceID` ASC),
  CONSTRAINT `fk_Departments_Budget1`
    FOREIGN KEY (`BudgetID`)
    REFERENCES `UPFinder`.`Budgets` (`BudgetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departments_Office1`
    FOREIGN KEY (`SpaceID`)
    REFERENCES `UPFinder`.`Offices` (`SpaceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`PDIs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`PDIs` (
  `UserID` INT NOT NULL,
  `DepartmentID` INT NOT NULL,
  `SpaceID` INT NOT NULL,
  `BudgetID` INT NOT NULL,
  `MemberOfGovTeam` TINYINT(1) NOT NULL,
  `LvlOfAccess` INT NULL DEFAULT 2,
  `Permanent` TINYINT(1) NULL,
  INDEX `fk_PDIs_Employees1_idx` (`UserID` ASC),
  PRIMARY KEY (`UserID`),
  INDEX `fk_PDIs_Departments1_idx` (`DepartmentID` ASC),
  INDEX `fk_PDIs_Office1_idx` (`SpaceID` ASC),
  INDEX `fk_PDIs_Budget1_idx` (`BudgetID` ASC),
  CONSTRAINT `fk_PDIs_Employees1`
    FOREIGN KEY (`UserID`)
    REFERENCES `UPFinder`.`Employees` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PDIs_Departments1`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `UPFinder`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PDIs_Office1`
    FOREIGN KEY (`SpaceID`)
    REFERENCES `UPFinder`.`Offices` (`SpaceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PDIs_Budget1`
    FOREIGN KEY (`BudgetID`)
    REFERENCES `UPFinder`.`Budgets` (`BudgetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `UPFinder`.`TFGs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`TFGs` (
  `TFGID` INT NOT NULL,
  `TFGName` VARCHAR(40) NULL,
  `Mark` INT NULL,
  `DegreeId` INT NOT NULL,
  `SupervisorId` INT NOT NULL,
  PRIMARY KEY (`TFGID`),
  INDEX `fk_TFG_Degree1_idx` (`DegreeId` ASC),
  INDEX `fk_TFG_PDIs1_idx` (`SupervisorId` ASC),
  CONSTRAINT `fk_TFG_Degree1`
    FOREIGN KEY (`DegreeId`)
    REFERENCES `UPFinder`.`Degrees` (`DegreeId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TFG_PDIs1`
    FOREIGN KEY (`SupervisorId`)
    REFERENCES `UPFinder`.`PDIs` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`Courses` (
  `CourseID` INT NOT NULL,
  `Name` VARCHAR(40) NULL,
  `StartingDate` DATE NULL,
  `EndingDate` DATE NULL,
  `ECTS` INT NULL,
  PRIMARY KEY (`CourseID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`contain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`contain` (
  `DegreeId` INT NOT NULL,
  `CourseID` INT NOT NULL,
  PRIMARY KEY (`DegreeId`, `CourseID`),
  INDEX `fk_Degree_has_Courses_Courses1_idx` (`CourseID` ASC),
  INDEX `fk_Degree_has_Courses_Degree1_idx` (`DegreeId` ASC),
  CONSTRAINT `fk_Degree_has_Courses_Degree1`
    FOREIGN KEY (`DegreeId`)
    REFERENCES `UPFinder`.`Degrees` (`DegreeId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Degree_has_Courses_Courses1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `UPFinder`.`Courses` (`CourseID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`Students` (
  `UserID` INT NOT NULL,
  `LvlOfAccess` INT NULL DEFAULT 1,
  PRIMARY KEY (`UserID`),
  INDEX `fk_Students_Users1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Students_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `UPFinder`.`Users` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `UPFinder`.`doing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`doing` (
  `CourseID` INT NOT NULL,
  `UserID` INT NOT NULL,
  `Mark` INT NULL,
  PRIMARY KEY (`CourseID`, `UserID`),
  INDEX `fk_Courses_has_Students_Courses1_idx` (`CourseID` ASC),
  INDEX `fk_Courses_has_Students_Students1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Courses_has_Students_Courses1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `UPFinder`.`Courses` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Students_Students1`
    FOREIGN KEY (`UserID`)
    REFERENCES `UPFinder`.`Students` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`CourseMaterials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`CourseMaterials` (
  `CourseMaterialID` INT NOT NULL,
  `CourseID` INT NOT NULL,
  PRIMARY KEY (`CourseMaterialID`),
  INDEX `fk_CourseMaterials_Courses1_idx` (`CourseID` ASC),
  CONSTRAINT `fk_CourseMaterials_Courses1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `UPFinder`.`Courses` (`CourseID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`teach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`teach` (
  `CourseID` INT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`CourseID`, `UserID`),
  INDEX `fk_Courses_has_PDIs_Courses1_idx` (`CourseID` ASC),
  INDEX `fk_Courses_has_PDIs_PDIs1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Courses_has_PDIs_Courses1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `UPFinder`.`Courses` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_PDIs_PDIs1`
    FOREIGN KEY (`UserID`)
    REFERENCES `UPFinder`.`PDIs` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`Classrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`Classrooms` (
  `SpaceID` INT NOT NULL,
  `Kind` VARCHAR(20) NULL DEFAULT NULL,
  INDEX `fk_Classrooms_Spaces1_idx` (`SpaceID` ASC),
  PRIMARY KEY (`SpaceID`),
  CONSTRAINT `fk_Classrooms_Spaces1`
    FOREIGN KEY (`SpaceID`)
    REFERENCES `UPFinder`.`Spaces` (`SpaceID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `UPFinder`.`PASs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`PASs` (
  `UserID` INT NOT NULL,
  `SystemID` INT NOT NULL,
  INDEX `fk_PASs_Employees1_idx` (`UserID` ASC),
  PRIMARY KEY (`UserID`),
  INDEX `fk_PASs_UniversityLogic1_idx` (`SystemID` ASC),
  CONSTRAINT `fk_PASs_Employees1`
    FOREIGN KEY (`UserID`)
    REFERENCES `UPFinder`.`Employees` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PASs_UniversityLogic1`
    FOREIGN KEY (`SystemID`)
    REFERENCES `UPFinder`.`UniversityLogic` (`SystemID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `UPFinder`.`enrolledTo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`enrolledTo` (
  `DegreeId` INT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`DegreeId`, `UserID`),
  INDEX `fk_Students_has_Degree_Degree1_idx` (`DegreeId` ASC),
  INDEX `fk_EnrolledTo_Students1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Students_has_Degree_Degree1`
    FOREIGN KEY (`DegreeId`)
    REFERENCES `UPFinder`.`Degrees` (`DegreeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EnrolledTo_Students1`
    FOREIGN KEY (`UserID`)
    REFERENCES `UPFinder`.`Students` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `UPFinder`.`WorkingPeriods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`WorkingPeriods` (
  `PeriodID` INT NOT NULL,
  `StartingDate` DATE NULL DEFAULT NULL,
  `EndingDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`PeriodID`));


-- -----------------------------------------------------
-- Table `UPFinder`.`contractedIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`contractedIn` (
  `UserID` INT NOT NULL,
  `PeriodID` INT NOT NULL,
  PRIMARY KEY (`UserID`, `PeriodID`),
  INDEX `fk_Employees_has_WorkingPeriods_WorkingPeriods1_idx` (`PeriodID` ASC),
  INDEX `fk_Employees_has_WorkingPeriods_Employees1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Employees_has_WorkingPeriods_Employees1`
    FOREIGN KEY (`UserID`)
    REFERENCES `UPFinder`.`Employees` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_has_WorkingPeriods_WorkingPeriods1`
    FOREIGN KEY (`PeriodID`)
    REFERENCES `UPFinder`.`WorkingPeriods` (`PeriodID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `UPFinder`.`BookingHours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`BookingHours` (
  `BookingId` INT NOT NULL,
  `UserID` INT NOT NULL,
  `StartingDate` DATE NOT NULL,
  `EndingDate` DATE NOT NULL,
  PRIMARY KEY (`BookingId`),
  INDEX `fk_BookingHours_Students1_idx` (`UserID` ASC),
  CONSTRAINT `fk_BookingHours_Students1`
    FOREIGN KEY (`UserID`)
    REFERENCES `UPFinder`.`Students` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`have`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`have` (
  `BookingId` INT NOT NULL,
  `SpaceID` INT NOT NULL,
  PRIMARY KEY (`BookingId`, `SpaceID`),
  INDEX `fk_BookingHours_has_LibraryWorkingArea_LibraryWorkingArea1_idx` (`SpaceID` ASC),
  INDEX `fk_BookingHours_has_LibraryWorkingArea_BookingHours1_idx` (`BookingId` ASC),
  CONSTRAINT `fk_BookingHours_has_LibraryWorkingArea_BookingHours1`
    FOREIGN KEY (`BookingId`)
    REFERENCES `UPFinder`.`BookingHours` (`BookingId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BookingHours_has_LibraryWorkingArea_LibraryWorkingArea1`
    FOREIGN KEY (`SpaceID`)
    REFERENCES `UPFinder`.`LibraryWorkingAreas` (`SpaceID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`ResearchProjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`ResearchProjects` (
  `ProjectId` INT NOT NULL,
  `Name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ProjectId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`doResearchIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`doResearchIn` (
  `UserID` INT NOT NULL,
  `ProjectId` INT NOT NULL,
  `IsPI` TINYINT(1) NOT NULL,
  PRIMARY KEY (`UserID`, `ProjectId`),
  INDEX `fk_PDIs_has_ResearchProject_ResearchProject1_idx` (`ProjectId` ASC),
  INDEX `fk_PDIs_has_ResearchProject_PDIs1_idx` (`UserID` ASC),
  CONSTRAINT `fk_PDIs_has_ResearchProject_PDIs1`
    FOREIGN KEY (`UserID`)
    REFERENCES `UPFinder`.`PDIs` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PDIs_has_ResearchProject_ResearchProject1`
    FOREIGN KEY (`ProjectId`)
    REFERENCES `UPFinder`.`ResearchProjects` (`ProjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `UPFinder`.`ResearchGrants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`ResearchGrants` (
  `GrantId` INT NOT NULL,
  `Name` VARCHAR(40) NOT NULL,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  `AmountMoney` FLOAT NULL,
  PRIMARY KEY (`GrantId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`areAssociated`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`areAssociated` (
  `GrantId` INT NOT NULL,
  `ProjectId` INT NOT NULL,
  PRIMARY KEY (`GrantId`, `ProjectId`),
  INDEX `fk_ResearchGrant_has_ResearchProject_ResearchProject1_idx` (`ProjectId` ASC),
  INDEX `fk_ResearchGrant_has_ResearchProject_ResearchGrant1_idx` (`GrantId` ASC),
  CONSTRAINT `fk_ResearchGrant_has_ResearchProject_ResearchGrant1`
    FOREIGN KEY (`GrantId`)
    REFERENCES `UPFinder`.`ResearchGrants` (`GrantId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ResearchGrant_has_ResearchProject_ResearchProject1`
    FOREIGN KEY (`ProjectId`)
    REFERENCES `UPFinder`.`ResearchProjects` (`ProjectId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`areDoneIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`areDoneIn` (
  `CourseID` INT NOT NULL,
  `SpaceID` INT NOT NULL,
  `StartTime` DATE NULL,
  `EndTime` DATE NULL,
  PRIMARY KEY (`CourseID`, `SpaceID`),
  INDEX `fk_Courses_has_Classrooms_Classrooms1_idx` (`SpaceID` ASC),
  INDEX `fk_Courses_has_Classrooms_Courses1_idx` (`CourseID` ASC),
  CONSTRAINT `fk_Courses_has_Classrooms_Courses1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `UPFinder`.`Courses` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Classrooms_Classrooms1`
    FOREIGN KEY (`SpaceID`)
    REFERENCES `UPFinder`.`Classrooms` (`SpaceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`Publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`Publications` (
  `PublicationID` INT NOT NULL,
  `Title` VARCHAR(40) NULL,
  `ProjectId` INT NOT NULL,
  PRIMARY KEY (`PublicationID`),
  INDEX `fk_Publications_ResearchProject1_idx` (`ProjectId` ASC),
  CONSTRAINT `fk_Publications_ResearchProject1`
    FOREIGN KEY (`ProjectId`)
    REFERENCES `UPFinder`.`ResearchProjects` (`ProjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`UniversityMaterials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`UniversityMaterials` (
  `UniversityMaterialID` INT NOT NULL,
  `Name` VARCHAR(20) NULL,
  `Availability` TINYINT(1) NULL,
  `StartingDate` DATE NULL,
  `EndingDate` DATE NULL,
  `SystemID` INT NOT NULL,
  PRIMARY KEY (`UniversityMaterialID`),
  INDEX `fk_UniversityMaterial_UniversityLogic1_idx` (`SystemID` ASC),
  CONSTRAINT `fk_UniversityMaterial_UniversityLogic1`
    FOREIGN KEY (`SystemID`)
    REFERENCES `UPFinder`.`UniversityLogic` (`SystemID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UPFinder`.`take`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UPFinder`.`take` (
  `UserID` INT NOT NULL,
  `UniversityMaterialID` INT NOT NULL,
  `Order` INT NULL,
  PRIMARY KEY (`UserID`, `UniversityMaterialID`),
  INDEX `fk_Students_has_UniversityMaterial_UniversityMaterial1_idx` (`UniversityMaterialID` ASC),
  INDEX `fk_Students_has_UniversityMaterial_Students1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Students_has_UniversityMaterial_Students1`
    FOREIGN KEY (`UserID`)
    REFERENCES `UPFinder`.`Students` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_UniversityMaterial_UniversityMaterial1`
    FOREIGN KEY (`UniversityMaterialID`)
    REFERENCES `UPFinder`.`UniversityMaterials` (`UniversityMaterialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
